### ISSUE TITLE
Crashes VS 2022 when using integrated Git tools to fix merge conflicts on MD files

### ISSUE THREAD

**Issue by olesakn** [madskristensen/MarkdownEditor2022#17]
As always, thanks for this great tool Mads! 

Hopefully the title is clear enough. I think I have uncovered an issue specific to VS 2022 git tools. 

When using the integrated Git features of Visual Studio 2022, the application hangs when merge any .md file via the integrated git diff tool. This was never an issue with 2019, so I am guessing there is something new in 2022 that is causing the issue. 

This can be reproduced by the following steps: 
1) Open a project in VS 2022 that has a git repo
2) Create a .md file
3) Create a branch - `md-troubleshooting`
4) Modify the .md file
5) Checkout the original branch
6) Modify the .md file again
7) Merge in `md-troubleshooting` branch, and you should have a merge conflict on the .md file. 
8) Use the integrated VS 2022 git tools to merge the conflicting .md file. The application should hang and require a force close. 

Note, the options to **Compare** files works fine. It's just the merge feature which breaks. 

Let me know if I can provide any more information!

**Comment by olesakn** [comment]
I did pull this error out of my windows application log, in case it helps: 

```
The description for Event ID 0 from source VSTTExecution cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

(devenv.exe, PID 71084, Thread 1) QualityToolsPackage Package Initialization Failure: Failed to get service EnvDTE._DTE.    at Microsoft.VisualStudio.TestTools.Vsip.VSServiceHelper.GetService[S,T](IServiceProvider serviceProvider)
   at Microsoft.VisualStudio.TestTools.Vsip.VSServiceHelper.GetPackageGuidForProjectType(IServiceProvider serviceProvider, Guid projectTypeGuid)
   at Microsoft.VisualStudio.TestTools.Vsip.TestProjectHelper.IsProjectTypeInstalled(IServiceProvider serviceProvider, Guid projectType)
   at Microsoft.VisualStudio.TestTools.Vsip.TestProjectHelper.GetDefaultTestProjectLanguage(IServiceProvider serviceProvider)
   at Microsoft.VisualStudio.TestTools.Vsip.TestProjectSettings..ctor(IServiceProvider serviceProvider)
   at Microsoft.VisualStudio.TestTools.TestCaseManagement.SolutionIntegrationManager.get_IsCmiEnabled()
   at Microsoft.VisualStudio.TestTools.TestCaseManagement.TestsDirtyStateManager..ctor()
   at Microsoft.VisualStudio.TestTools.TestCaseManagement.QualityToolsPackage.<InitializeAsync>d__20.MoveNext()

The message resource is present but the message was not found in the message table

```
